apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-k8s
spec:
  serviceName: test-k8s
  replicas: 3
  selector:
    matchLabels:
      app: test-k8s
  template:
    metadata:
      labels:
        app: test-k8s
    spec:
      containers:
        - name: test-k8s
          image: haronka/test-k8s:v1
          ports:
            - containerPort: 8080
          # Add any environment variables or volumes needed.
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
